import {test, expect} from '@playwright/test'

test.beforeEach(async({page}) => {

//    await page.goto('https://youtube.com');
//    await page.waitForLoadState('networkidle');
    await page.goto('https://demo.playwright.dev/todomvc');
});

// Configure the describe block to run tests in parallel
test.describe.configure({ mode: 'parallel', });

const TODO_items = [
    "1, buy some cheese"
    ,"2, feed the cat"
    ,"3, book a doctor's appointment"
    ,"4, call mom"
    ,"5, finish reading a book"
    ,"6, water the plants"
    ,"7, clean the kitchen"
    ,"8, write a blog post"
    ,"9, reply to emails"
    ,"10, exercise for 30 minutes"
    ,"11, grocery shopping"
//    ,"12, take out the trash"
//    ,"13, schedule a dentist appointment"
//    ,"14, update LinkedIn profile"
//    ,"15, plan the weekend trip"
//    ,"16, pay electricity bill"
//    ,"17, declutter the workspace"
//    ,"18, cook a new recipe"
//    ,"19, organize closet"
//    ,"20, back up laptop files"
//    ,"21, check car tire pressure"
//    ,"22, meditate for 10 minutes"
//    ,"23, send a thank-you note"
//    ,"24, walk the dog"
//    ,"25, review bank statements"
//    ,"26, prepare a presentation"
//    ,"27, schedule an oil change"
//    ,"28, buy a birthday gift"
//    ,"29, set up a workout plan"
//    ,"30, vacuum the living room"
//    ,"31, fix the leaky faucet"
//    ,"32, read industry news"
//    ,"33, follow up on pending tasks"
//    ,"34, write a journal entry"
//    ,"35, plan next week’s meals"
//    ,"36, call an old friend"
//    ,"37, attend a networking event"
//    ,"38, watch an educational video"
//    ,"39, check credit score"
//    ,"40, renew library books"
//    ,"41, practice a new language"
//    ,"42, prepare tax documents"
//    ,"43, send a feedback request"
//    ,"44, update software on devices"
//    ,"45, change bedsheets"
//    ,"46, write a poem"
//    ,"47, plant a tree"
//    ,"48, listen to a new podcast"
//    ,"49, book a yoga class"
//    ,"50, set a savings goal"
//    ,"51, check home security system"
//    ,"52, buy new running shoes"
//    ,"53, review emergency contacts"
//    ,"54, fix the broken chair"
//    ,"55, scan and organize receipts"
//    ,"56, visit a museum"
//    ,"57, try a new restaurant"
//    ,"58, start a new hobby"
//    ,"59, unsubscribe from spam emails"
//    ,"60, clean the car"
//    ,"61, do a digital detox for an hour"
//    ,"62, review personal goals"
//    ,"63, write a thank-you letter"
//    ,"64, check social media settings"
//    ,"65, learn a new Excel function"
//    ,"66, donate old clothes"
//    ,"67, update resume"
//    ,"68, start a side project"
//    ,"69, rearrange furniture"
//    ,"70, deep clean the bathroom"
//    ,"71, update passwords"
//    ,"72, join a book club"
//    ,"73, learn a new recipe"
//    ,"74, watch a TED Talk"
//    ,"75, buy a houseplant"
//    ,"76, visit a new park"
//    ,"77, organize photo albums"
//    ,"78, host a game night"
//    ,"79, write a short story"
//    ,"80, set up a morning routine"
//    ,"81, review insurance policies"
//    ,"82, start meal prepping"
//    ,"83, test smoke alarms"
//    ,"84, try a new workout routine"
//    ,"85, set up automatic bill payments"
//    ,"86, create a bucket list"
//    ,"87, spend time offline"
//    ,"88, learn about investments"
//    ,"89, try a DIY project"
//    ,"90, journal about gratitude"
//    ,"91, make a playlist"
//    ,"92, check weather for the week"
//    ,"93, create a home budget"
//    ,"94, write a motivational note"
//    ,"95, plan a picnic"
//    ,"96, support a local business"
//    ,"97, meditate for relaxation"
//    ,"98, sort and donate books"
//    ,"99, learn a magic trick"
//    ,"100, clean up the desktop files"
//    ,"101, write a handwritten letter"
//    ,"102, research a new travel destination"
//    ,"103, create a daily schedule"
//    ,"104, repaint the living room"
//    ,"105, set up a new email signature"
//    ,"106, buy a new book"
//    ,"107, fix a slow laptop"
//    ,"108, learn how to solve a Rubik’s cube"
//    ,"109, make homemade pizza"
//    ,"110, organize the spice rack"
//    ,"111, stretch for 10 minutes"
//    ,"112, update emergency kit"
//    ,"113, build a habit tracker"
//    ,"114, try origami"
//    ,"115, learn to juggle"
//    ,"116, clean out the fridge"
//    ,"117, do 50 push-ups"
//    ,"118, write a limerick"
//    ,"119, create a vision board"
//    ,"120, solve a Sudoku puzzle"
//    ,"121, watch a classic movie"
//    ,"122, find a new favorite coffee shop"
//    ,"123, write a fan letter"
//    ,"124, create a photo collage"
//    ,"125, test all home locks"
//    ,"126, plan a staycation"
//    ,"127, try a different route to work"
//    ,"128, learn to whistle with fingers"
//    ,"129, write down 5 positive affirmations"
//    ,"130, make a time capsule"
//    ,"131, find a new music genre"
//    ,"132, try a cold shower challenge"
//    ,"133, research how airplanes work"
//    ,"134, try a 24-hour no-phone challenge"
//    ,"135, learn to make latte art"
//    ,"136, plant a vegetable garden"
//    ,"137, visit an animal shelter"
//    ,"138, bake cookies for a neighbor"
//    ,"139, take a different morning routine"
//    ,"140, try a new ice cream flavor"
//    ,"141, create a crossword puzzle"
//    ,"142, build a birdhouse"
//    ,"143, learn about space exploration"
//    ,"144, try writing a short song"
//    ,"145, handwrite a letter to yourself"
//    ,"146, explore an online museum"
//    ,"147, identify constellations in the night sky"
//    ,"148, listen to a full album without distraction"
//    ,"149, practice deep breathing exercises"
//    ,"150, find a new productivity hack"
//    ,"151, memorize a motivational quote"
//    ,"152, try a new smoothie recipe"
//    ,"153, learn about a random historical event"
//    ,"154, test a free online course"
//    ,"155, try shadow drawing"
//    ,"156, create a fake business plan for fun"
//    ,"157, learn a new keyboard shortcut"
//    ,"158, find out how a specific app is built"
//    ,"159, test your typing speed"
//    ,"160, learn to tie a new type of knot"
//    ,"161, create a personal mantra"
//    ,"162, read a short story from a different culture"
//    ,"163, practice ambidexterity"
//    ,"164, write an alternate ending to a movie"
//    ,"165, research why cats purr"
//    ,"166, find a new way to wrap a gift"
//    ,"167, watch a foreign language film"
//    ,"168, read about the deepest ocean trench"
//    ,"169, write a review of the last book you read"
//    ,"170, create a mock travel itinerary"
//    ,"171, rearrange your bookshelf by color"
//    ,"172, try a different way to tie shoelaces"
//    ,"173, explore an unusual Wikipedia article"
//    ,"174, write down your top 3 happiest memories"
//    ,"175, learn how a camera works"
//    ,"176, take a completely different walking path"
//    ,"177, search for bizarre world records"
//    ,"178, learn a new pen spinning trick"
//    ,"179, draw a map of your neighborhood"
//    ,"180, practice mirror writing"
//    ,"181, try a tongue twister in another language"
//    ,"182, make up a conspiracy theory for fun"
//    ,"183, try sleeping in a different position"
//    ,"184, study different cloud types"
//    ,"185, create a fictional superhero""186, buy some cheese"
//    ,"187, feed the cat"
//    ,"188, book a doctor's appointment"
//    ,"189, call mom"
//    ,"190, finish reading a book"
//    ,"191, water the plants"
//    ,"192, clean the kitchen"
//    ,"193, write a blog post"
//    ,"194, reply to emails"
//    ,"195, exercise for 30 minutes"
//    ,"196, grocery shopping"
//    ,"197, take out the trash"
//    ,"198, schedule a dentist appointment"
//    ,"199, update LinkedIn profile"
//    ,"200, plan the weekend trip"
//    ,"201, pay electricity bill"
//    ,"202, declutter the workspace"
//    ,"203, cook a new recipe"
//    ,"204, organize closet"
//    ,"205, back up laptop files"
//    ,"206, check car tire pressure"
//    ,"207, meditate for 10 minutes"
//    ,"208, send a thank-you note"
//    ,"209, walk the dog"
//    ,"210, review bank statements"
//    ,"211, prepare a presentation"
//    ,"212, schedule an oil change"
//    ,"213, buy a birthday gift"
//    ,"214, set up a workout plan"
//    ,"215, vacuum the living room"
//    ,"216, fix the leaky faucet"
//    ,"217, read industry news"
//    ,"218, follow up on pending tasks"
//    ,"219, write a journal entry"
//    ,"220, plan next week’s meals"
//    ,"221, call an old friend"
//    ,"222, attend a networking event"
//    ,"223, watch an educational video"
//    ,"224, check credit score"
//    ,"225, renew library books"
//    ,"226, practice a new language"
//    ,"227, prepare tax documents"
//    ,"228, send a feedback request"
//    ,"229, update software on devices"
//    ,"230, change bedsheets"
//    ,"231, write a poem"
//    ,"232, plant a tree"
//    ,"233, listen to a new podcast"
//    ,"234, book a yoga class"
//    ,"235, set a savings goal"
//    ,"236, check home security system"
//    ,"237, buy new running shoes"
//    ,"238, review emergency contacts"
//    ,"239, fix the broken chair"
//    ,"240, scan and organize receipts"
//    ,"241, visit a museum"
//    ,"242, try a new restaurant"
//    ,"243, start a new hobby"
//    ,"244, unsubscribe from spam emails"
//    ,"245, clean the car"
//    ,"246, do a digital detox for an hour"
//    ,"247, review personal goals"
//    ,"248, write a thank-you letter"
//    ,"249, check social media settings"
//    ,"250, learn a new Excel function"
//    ,"251, donate old clothes"
//    ,"252, update resume"
//    ,"253, start a side project"
//    ,"254, rearrange furniture"
//    ,"255, deep clean the bathroom"
//    ,"256, update passwords"
//    ,"257, join a book club"
//    ,"258, learn a new recipe"
//    ,"259, watch a TED Talk"
//    ,"260, buy a houseplant"
//    ,"261, visit a new park"
//    ,"262, organize photo albums"
//    ,"263, host a game night"
//    ,"264, write a short story"
//    ,"265, set up a morning routine"
//    ,"266, review insurance policies"
//    ,"267, start meal prepping"
//    ,"268, test smoke alarms"
//    ,"269, try a new workout routine"
//    ,"270, set up automatic bill payments"
//    ,"271, create a bucket list"
//    ,"272, spend time offline"
//    ,"273, learn about investments"
//    ,"274, try a DIY project"
//    ,"275, journal about gratitude"
//    ,"276, make a playlist"
//    ,"277, check weather for the week"
//    ,"278, create a home budget"
//    ,"279, write a motivational note"
//    ,"280, plan a picnic"
//    ,"281, support a local business"
//    ,"282, meditate for relaxation"
//    ,"283, sort and donate books"
//    ,"284, learn a magic trick"
//    ,"285, clean up the desktop files"
//    ,"286, write a handwritten letter"
//    ,"287, research a new travel destination"
//    ,"288, create a daily schedule"
//    ,"289, repaint the living room"
//    ,"290, set up a new email signature"
//    ,"291, buy a new book"
//    ,"292, fix a slow laptop"
//    ,"293, learn how to solve a Rubik’s cube"
//    ,"294, make homemade pizza"
//    ,"295, organize the spice rack"
//    ,"296, stretch for 10 minutes"
//    ,"297, update emergency kit"
//    ,"298, build a habit tracker"
//    ,"299, try origami"
//    ,"300, learn to juggle"
//    ,"301, clean out the fridge"
//    ,"302, do 50 push-ups"
//    ,"303, write a limerick"
//    ,"304, create a vision board"
//    ,"305, solve a Sudoku puzzle"
//    ,"306, watch a classic movie"
//    ,"307, find a new favorite coffee shop"
//    ,"308, write a fan letter"
//    ,"309, create a photo collage"
//    ,"310, test all home locks"
//    ,"311, plan a staycation"
//    ,"312, try a different route to work"
//    ,"313, learn to whistle with fingers"
//    ,"314, write down 5 positive affirmations"
//    ,"315, make a time capsule"
//    ,"316, find a new music genre"
//    ,"317, try a cold shower challenge"
//    ,"318, research how airplanes work"
//    ,"319, try a 24-hour no-phone challenge"
//    ,"320, learn to make latte art"
//    ,"321, plant a vegetable garden"
//    ,"322, visit an animal shelter"
//    ,"323, bake cookies for a neighbor"
//    ,"324, take a different morning routine"
//    ,"325, try a new ice cream flavor"
//    ,"326, create a crossword puzzle"
//    ,"327, build a birdhouse"
//    ,"328, learn about space exploration"
//    ,"329, try writing a short song"
//    ,"330, handwrite a letter to yourself"
//    ,"331, explore an online museum"
//    ,"332, identify constellations in the night sky"
//    ,"333, listen to a full album without distraction"
//    ,"334, practice deep breathing exercises"
//    ,"335, find a new productivity hack"
//    ,"336, memorize a motivational quote"
//    ,"337, try a new smoothie recipe"
//    ,"338, learn about a random historical event"
//    ,"339, test a free online course"
//    ,"340, try shadow drawing"
//    ,"341, create a fake business plan for fun"
//    ,"342, learn a new keyboard shortcut"
//    ,"343, find out how a specific app is built"
//    ,"344, test your typing speed"
//    ,"345, learn to tie a new type of knot"
//    ,"346, create a personal mantra"
//    ,"347, read a short story from a different culture"
//    ,"348, practice ambidexterity"
//    ,"349, write an alternate ending to a movie"
//    ,"350, research why cats purr"
//    ,"351, find a new way to wrap a gift"
//    ,"352, watch a foreign language film"
//    ,"353, read about the deepest ocean trench"
//    ,"354, write a review of the last book you read"
//    ,"355, create a mock travel itinerary"
//    ,"356, rearrange your bookshelf by color"
//    ,"357, try a different way to tie shoelaces"
//    ,"358, explore an unusual Wikipedia article"
//    ,"359, write down your top 3 happiest memories"
//    ,"360, learn how a camera works"
//    ,"361, take a completely different walking path"
//    ,"362, search for bizarre world records"
//    ,"363, learn a new pen spinning trick"
//    ,"364, draw a map of your neighborhood"
//    ,"365, practice mirror writing"
//    ,"366, try a tongue twister in another language"
//    ,"367, make up a conspiracy theory for fun"
//    ,"368, try sleeping in a different position"
//    ,"369, study different cloud types"
//    ,"370, create a fictional superhero"
//    ,"371, build a tiny model house"
//    ,"372, read about an ancient civilization"
//    ,"373, write a funny joke"
//    ,"374, test a life hack"
//    ,"375, make a collage of childhood photos"
//    ,"376, write a personal manifesto"
//    ,"377, find out how submarines work"
//    ,"378, try a new cooking method"
//    ,"379, read a scientific paper"
//    ,"380, learn how different countries drink coffee"
];

test.describe.parallel('New TODO', () => {


        TODO_items.forEach(todo => {
    test(`Should allow todo to be created ${todo}`, async({page}) =>{

        await page.getByPlaceholder('What needs to be done?').fill(todo);
        await page.waitForTimeout(1000);

        });

    });

});